ci: update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,6 +11,12 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Display Actor
+      run: echo "${{ github.actor }} is launching pipeline"
+
+    - name: Display Start Time Pipeline
+      run: echo "Pipeline started at $(date +'%H:%M:%S')"
+      
     - name: Checkout repository
       uses: actions/checkout@v2
 
@@ -22,5 +28,28 @@ jobs:
     - name: Install dependencies
       run: npm install
 
-    - name: Run tests
-      run: npm run test
+    - name: Run Prettier
+      run: npm run prettier
+
+    - name: Run ESLint
+      run: npm run lint
+
+    - name: Run tests and check coverage
+      run: |
+          npm run test -- --coverage
+          COVERAGE=$(cat coverage/lcov-report/index.html | grep -oP 'Statements<\/td><td class="text-right"><strong>\K\d+')
+          if [ "$COVERAGE" -ge 80 ]; then
+            echo "Code coverage is above 80%: $COVERAGE%"
+          else
+            echo "Code coverage is below 80%: $COVERAGE%"
+            exit 1
+          fi
+          
+    - name: Build Project
+      run: npm run build
+
+    - name: Display End Time Pipeline
+      run: echo "Pipeline finished at $(date +'%H:%M:%S')"
+
+    - name: Display Success Message
+      run: echo "PIPELINE SUCCESS WITHOUT ERRORS"
